settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: cron-server
  path: .
  commands:
    build:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
    - cron-server
    - cron-server-go-tmp-umask
